---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/kshah-ebc-test/istio-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
