apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: kshah-ebc-test
  secretRef:
    name: flux-system
  url: https://github.com/retaildevcrews/pib-gitops
