apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  selector:
    app: {{gitops.name}}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
