app: imdb
environment: dev
image: ghcr.io/cse-labs/imdb-app:latest
imageName: ghcr.io/cse-labs/imdb-app
imageTag: latest
name: imdb
namespace: imdb
port: 8080
target: dev
targets:
    - all
template: pib-service-canary
workspace: imdb
