apiVersion: v1
kind: ConfigMap
metadata:
  name: flagger-grafana-datasources
  namespace: istio-system
data:
  datasources.yaml: |-
    apiVersion: 1

    deleteDatasources:
      - name: prometheus
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.istio-system:9090
      isDefault: true
      editable: true
      version: 1
