template: .gitops
deployments:
  dev:
    target: dev
    values:
      app: istio
      environment: dev
      name: istio
      namespace: istio-system
      targets: [ all ]
      workspace: istio-system
