apiVersion: v1
kind: Service
metadata:
  name: flagger-grafana
  namespace: istio-system
  labels:
    app: grafana
    chart: grafana-1.7.0
    release: flagger-grafana
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: flagger-grafana
    release: flagger-grafana

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flagger-grafana-vs
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /grafana
    route:
    - destination:
        host: flagger-grafana
