namespace: istio-system
commonLabels:
  app: {{gitops.name}}
resources:
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
  - prometheus.yaml
images:
  - name: {{gitops.imageName}}
    newName: {{gitops.imageName}}
    newTag: {{gitops.imageTag}}
