app: badapp
environment: dev
image: ghcr.io/retaildevcrews/heartbeat:latest
imageName: ghcr.io/retaildevcrews/heartbeat
imageTag: latest
name: badapp
namespace: badapp
target: dev
targets: [ ]
workspace: badapp
