apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.app}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.app}}
  template:
    metadata:
      labels:
        app: {{gitops.app}}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: {{gitops.app}}
          image: {{gitops.image}}
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
