apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upload
  namespace: voe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
