apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/apps/central-bartr-test-102
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
