apiVersion: v1
kind: Service
metadata:
  name: {{coral.app}}
  namespace: {{coral.namespace}}
spec:
  selector:
    app: {{coral.app}}
  ports:
    - protocol: TCP
      port: {{coral.port}}
      targetPort: {{coral.port}}
