namespace: istio-system
commonLabels:
  app: {{gitops.name}}
resources:
  - account.yaml
  - rbac.yaml
  - crd.yaml
  - deployment.yaml
  - prometheus.yaml
images:
  - name: ghcr.io/fluxcd/flagger
    newName: ghcr.io/fluxcd/flagger
    newTag: 1.21.0
