template: .gitops
deployments:
  dev:
    target: dev
    values:
      name: flux-system
      namespace: flux-system
      workspace: flux-system
      repo: retaildevcrews/gitops-template
      branch: kshah-image-test
      targets: [ all ]
