template: .gitops
deployments:
  dev:
    target: dev
    values:
      name: flux-system
      namespace: flux-system
      workspace: flux-system
      repo: retaildevcrews/pib-gitops
      branch: kshah-ebc-test
      targets: [ all ]
