template: .gitops
deployments:
    dev:
        target: dev
        values:
            environment: dev
            name: flagger-grafana
            namespace: istio-system
            subpath: /grafana
            targets:
                - all
            workspace: istio-system
