#!/bin/bash

if [ "$1" == "" ]
then
    echo "Error: /path is required"
    echo "usage: flt curl /path"
else
    if [ "$AKDC_SSL" = "" ]
    then
        curl -s http://"$AKDC_FQDN$1"
    else
        curl -s https://"$AKDC_FQDN$1"
    fi
fi
