#!/bin/bash

rg=$1

if [ "$rg" = "" ]
then
    rg="$FLT_RG"
fi

if [ "$rg" = "" ]
then
    rg="$(git branch --show-current)"
fi

if [ "$rg" = "" ]
then
    echo "usage: flt az vms resourceGroup"
    exit 0
fi

echo ""
echo "getting VMs in resource group: $rg"
echo ""

hdrsort()
{
    read -r
    printf "%s\\n" "$REPLY"
    sort
}

az vm list --query '[].name' -o table -g "$rg" | hdrsort
