apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.app}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.app}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{gitops.app}}
  template:
    metadata:
      labels:
        app: {{gitops.app}}
    spec:
      containers:
      - name: {{gitops.app}}
        image: {{gitops.image}}
        imagePullPolicy: Always
        env:
        - name: TITLE
          value: {{gitops.title}}
        - name: KEY1
          value: {{gitops.key1}}
        - name: KEY2
          value: {{gitops.key2}}
        ports:
        - containerPort: {{gitops.port}}
        resources:
          limits:
            cpu: 200m
            memory: 64Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{gitops.port}}
          initialDelaySeconds: 10
          periodSeconds: 10
