apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{gitops.app}}-vs
  namespace: {{gitops.namespace}}
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{gitops.app}}
            port:
              number: {{gitops.port}}
